const videoData = [
  {
    id: 1,
    thumbnail: "",
    title: "Intro",
    videoSrc: "",
    released: true,
    description: "XXFXGXHX",
  },
  {
    id: 2,
    thumbnail: "",
    title: "Mathaye Haath",
    videoSrc: "",
    released: true,
    description: "HDJYDTJHGC",
  },
  {
    id: 13,
    thumbnail: "",
    title: "Tara Kor",
    videoSrc: "",
    released: false,
    description: "UODTYXTYXY",
  },
  {
    id: 4,
    thumbnail: "",
    title: "3 Chokka",
    videoSrc: "",
    released: false,
    description: "",
  },
  {
    id: 5,
    thumbnail: "",
    title: "Circle",
    videoSrc: "",
    released: false,
    description: "",
  },
  {
    id: 6,
    thumbnail: "",
    title: "Kara Bhai",
    videoSrc: "",
    released: false,
    description: "",
  },
  {
    id: 7,
    thumbnail: "",
    title: "Dewale Pith",
    videoSrc: "",
    released: false,
    description: "",
  },
  {
    id: 8,
    thumbnail: "",
    title: "Ces't La Vie",
    videoSrc: "",
    released: false,
    description: "",
  },
  {
    id: 9,
    thumbnail: "",
    title: "Outro",
    videoSrc: "",
    released: false,
    description: "",
  },
];

export default videoData;
